engines:
  eslint:
    enabled: true
    channel: eslint-5
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - BUG
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  scss-lint:
    enabled: true
  shellcheck:
    enabled: false
ratings:
  paths:
  - libs/**
  - "**.css"
  - "**.scss"
exclude_paths:
- "@ks89"
- "node_modules/"
- ".github/"
- "travisci/"
- ".travis.yml"
- ".sass-lint.yml"
- ".editorconfig"
- ".npmignore"
- ".prettierignore"
- ".prettierrc.json"
- "*.ngfactory.ts"
- "*.ngsummary.json"
- "examples/"
- "apps/"
- "docs/"
- "coverage/"
- "**/*.log"
- "**/e2e/"
- "**/*.spec.ts"
