name: angular-modal-gallery

on:
  push:
    paths-ignore:
    - 'node_modules'
    - 'examples/angular-cli-12/node_modules'
    - 'examples/angular-cli-material/node_modules'
    - 'examples/universal/node_modules'

jobs:

  angular-modal-gallery:
    name: "angular-modal-gallery"
    timeout-minutes: 10

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Switch to a specific npm version
      run: |
        npm install -g npm@7
        npm cache verify
        npm prune
        npm update

    - name: Installling all deps
      run: |
        cd examples/angular-cli-12
        npm ci
        cd ../..
        cd examples/angular-cli-material
        npm ci
        cd ../..
        cd examples/universal
        npm ci
        cd ../..

    - name: Building web applications
      run: |
        npm run build:all
        npm run build:main:dev
        npm run build:main:prod
        cd examples/angular-cli-12
        npm run build:dev
        npm run build:prod
        cd ../..
        cd examples/angular-cli-material
        npm run build:dev
        npm run build:prod
        cd ../..
        cd examples/universal
        npm run build:dev
        npm run build:prod
        npm run build:ssr
        npm run prerender
        cd ../..

    - name: Running tests
      run: |
        npm run test:ci
